VAL_DIR: "/nfs/data/nii/data1/Analysis/GPUnet/ANALYSIS_incontext/SegFM3D/3D_train_npz_random_10percent_16G/CT/CT_Abdomen1K"
RESULTS_DIR: "/nfs/data/nii/data1/Analysis/GPUnet/ANALYSIS_incontext/SegFM3D/results"

SAM_CKPT_PATH: "/nfs/norasys/notebooks/camaret/SAM-Med3D/ckpt/sam_med3d_turbo_bbox_cvpr.pth"
SAM_REPO_DIR: "/nfs/norasys/notebooks/camaret/SAM-Med3D"